const mongoose = require('mongoose');
const Gender = require('../models/Genders');
const Country = require('../models/Countries');
const Review = require('../models/Review');
const Log = require('../libs/log');
const keys = require('../config/keys');

const genders = [
    {name: 'male', type: 1},
    {name: 'female', type: 2}
];

const countries = [
    {name: "AALAND ISLANDS"},
	{name: "AFGHANISTAN"},
	{name: "ALBANIA"},
	{name: "ALGERIA"},
	{name: "AMERICAN SAMOA"},
	{name: "ANDORRA"},
	{name: "ANGOLA"},
	{name: "ANGUILLA"},
	{name: "ANTARCTICA"},
	{name: "ANTIGUA AND BARBUDA"},
	{name: "ARGENTINA"},
	{name: "ARMENIA"},
	{name: "ARUBA"},
	{name: "AUSTRALIA"},
	{name: "AUSTRIA"},
	{name: "AZERBAIJAN"},
	{name: "BAHAMAS"},
	{name: "BAHRAIN"},
	{name: "BANGLADESH"},
	{name: "BARBADOS"},
	{name: "BELARUS"},
	{name: "BELGIUM"},
	{name: "BELIZE"},
	{name: "BENIN"},
	{name: "BERMUDA"},
	{name: "BHUTAN"},
	{name: "BOLIVIA"},
	{name: "BOSNIA AND HERZEGOWINA"},
	{name: "BOTSWANA"},
	{name: "BOUVET ISLAND"},
	{name: "BRAZIL"},
	{name: "BRITISH INDIAN OCEAN TERRITORY"},
	{name: "BRUNEI DARUSSALAM"},
	{name: "BULGARIA"},
	{name: "BURKINA FASO"},
	{name: "BURUNDI"},
	{name: "CAMBODIA"},
	{name: "CAMEROON"},
	{name: "CANADA"},
	{name: "CAPE VERDE"},
	{name: "CAYMAN ISLANDS"},
	{name: "CENTRAL AFRICAN REPUBLIC"},
	{name: "CHAD"},
	{name: "CHILE"},
	{name: "CHINA"},
	{name: "CHRISTMAS ISLAND"},
	{name: "COLOMBIA"},
	{name: "COMOROS"},
	{name: "COOK ISLANDS"},
	{name: "COSTA RICA"},
	{name: "COTE D'IVOIRE"},
	{name: "CUBA"},
	{name: "CYPRUS"},
	{name: "CZECH REPUBLIC"},
	{name: "DENMARK"},
	{name: "DJIBOUTI"},
	{name: "DOMINICA"},
	{name: "DOMINICAN REPUBLIC"},
	{name: "ECUADOR"},
	{name: "EGYPT"},
	{name: "EL SALVADOR"},
	{name: "EQUATORIAL GUINEA"},
	{name: "ERITREA"},
	{name: "ESTONIA"},
	{name: "ETHIOPIA"},
	{name: "FAROE ISLANDS"},
	{name: "FIJI"},
	{name: "FINLAND"},
	{name: "FRANCE"},
	{name: "FRENCH GUIANA"},
	{name: "FRENCH POLYNESIA"},
	{name: "FRENCH SOUTHERN TERRITORIES"},
	{name: "GABON"},
	{name: "GAMBIA"},
	{name: "GEORGIA"},
	{name: "GERMANY"},
	{name: "GHANA"},
	{name: "GIBRALTAR"},
	{name: "GREECE"},
	{name: "GREENLAND"},
	{name: "GRENADA"},
	{name: "GUADELOUPE"},
	{name: "GUAM"},
	{name: "GUATEMALA"},
	{name: "GUINEA"},
	{name: "GUINEA-BISSAU"},
	{name: "GUYANA"},
	{name: "HAITI"},
	{name: "HEARD AND MC DONALD ISLANDS"},
	{name: "HONDURAS"},
	{name: "HONG KONG"},
	{name: "HUNGARY"},
	{name: "ICELAND"},
	{name: "INDIA"},
	{name: "INDONESIA"},
	{name: "IRAQ"},
	{name: "IRELAND"},
	{name: "ISRAEL"},
	{name: "ITALY"},
	{name: "JAMAICA"},
	{name: "JAPAN"},
	{name: "JORDAN"},
	{name: "KAZAKHSTAN"},
	{name: "KENYA"},
	{name: "KIRIBATI"},
	{name: "KUWAIT"},
	{name: "KYRGYZSTAN"},
	{name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
	{name: "LATVIA"},
	{name: "LEBANON"},
	{name: "LESOTHO"},
	{name: "LIBERIA"},
	{name: "LIBYAN ARAB JAMAHIRIYA"},
	{name: "LIECHTENSTEIN"},
	{name: "LITHUANIA"},
	{name: "LUXEMBOURG"},
	{name: "MACAU"},
	{name: "MADAGASCAR"},
	{name: "MALAWI"},
	{name: "MALAYSIA"},
	{name: "MALDIVES"},
	{name: "MALI"},
	{name: "MALTA"},
	{name: "MARSHALL ISLANDS"},
	{name: "MARTINIQUE"},
	{name: "MAURITANIA"},
	{name: "MAURITIUS"},
	{name: "MAYOTTE"},
	{name: "MEXICO"},
	{name: "MONACO"},
	{name: "MONGOLIA"},
	{name: "MONTSERRAT"},
	{name: "MOROCCO"},
	{name: "MOZAMBIQUE"},
	{name: "MYANMAR"},
	{name: "NAMIBIA"},
	{name: "NAURU"},
	{name: "NEPAL"},
	{name: "NETHERLANDS"},
	{name: "NETHERLANDS ANTILLES"},
	{name: "NEW CALEDONIA"},
	{name: "NEW ZEALAND"},
	{name: "NICARAGUA"},
	{name: "NIGER"},
	{name: "NIGERIA"},
	{name: "NIUE"},
	{name: "NORFOLK ISLAND"},
	{name: "NORTHERN MARIANA ISLANDS"},
	{name: "NORWAY"},
	{name: "OMAN"},
	{name: "PAKISTAN"},
	{name: "PALAU"},
	{name: "PANAMA"},
	{name: "PAPUA NEW GUINEA"},
	{name: "PARAGUAY"},
	{name: "PERU"},
	{name: "PHILIPPINES"},
	{name: "PITCAIRN"},
	{name: "POLAND"},
	{name: "PORTUGAL"},
	{name: "PUERTO RICO"},
	{name: "QATAR"},
	{name: "REUNION"},
	{name: "ROMANIA"},
	{name: "RUSSIAN FEDERATION"},
	{name: "RWANDA"},
	{name: "SAINT HELENA"},
	{name: "SAINT KITTS AND NEVIS"},
	{name: "SAINT LUCIA"},
	{name: "SAINT PIERRE AND MIQUELON"},
	{name: "SAINT VINCENT AND THE GRENADINES"},
	{name: "SAMOA"},
	{name: "SAN MARINO"},
	{name: "SAO TOME AND PRINCIPE"},
	{name: "SAUDI ARABIA"},
	{name: "SENEGAL"},
	{name: "SERBIA AND MONTENEGRO"},
	{name: "SEYCHELLES"},
	{name: "SIERRA LEONE"},
	{name: "SINGAPORE"},
	{name: "SLOVAKIA"},
	{name: "SLOVENIA"},
	{name: "SOLOMON ISLANDS"},
	{name: "SOMALIA"},
	{name: "SOUTH AFRICA"},
	{name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"},
	{name: "SPAIN"},
	{name: "SRI LANKA"},
	{name: "SUDAN"},
	{name: "SURINAME"},
	{name: "SVALBARD AND JAN MAYEN ISLANDS"},
	{name: "SWAZILAND"},
	{name: "SWEDEN"},
	{name: "SWITZERLAND"},
	{name: "SYRIAN ARAB REPUBLIC"},
	{name: "TAIWAN"},
	{name: "TAJIKISTAN"},
	{name: "THAILAND"},
	{name: "TIMOR-LESTE"},
	{name: "TOGO"},
	{name: "TOKELAU"},
	{name: "TONGA"},
	{name: "TRINIDAD AND TOBAGO"},
	{name: "TUNISIA"},
	{name: "TURKEY"},
	{name: "TURKMENISTAN"},
	{name: "TURKS AND CAICOS ISLANDS"},
	{name: "TUVALU"},
	{name: "UGANDA"},
	{name: "UKRAINE"},
	{name: "UNITED ARAB EMIRATES"},
	{name: "UNITED KINGDOM"},
	{name: "UNITED STATES"},
	{name: "UNITED STATES MINOR OUTLYING ISLANDS"},
	{name: "URUGUAY"},
	{name: "UZBEKISTAN"},
	{name: "VANUATU"},
	{name: "VENEZUELA"},
	{name: "VIET NAM"},
	{name: "WALLIS AND FUTUNA ISLANDS"},
	{name: "WESTERN SAHARA"},
	{name: "YEMEN"},
	{name: "ZAMBIA"},
	{name: "ZIMBABWE"},
];

const feadBack = [
    {
        "age": 22,
        "gender": 1,
        "country": "ZAMBIA",
        "orign_page": "http://localhost:4200",
        "note": "test",
        "name": "test 1",
        "email": "test1@mail.ru",
        "rating": 3
    },
    {
        "age": 34,
        "gender": 2,
        "country": "ZAMBIA",
        "orign_page": "http://localhost:4200",
        "note": "test 2",
        "name": "test 2",
        "email": "test2@mail.ru",
        "rating": 5
    },
    {
        "age": 29,
        "gender": 1,
        "country": "UKRAINE",
        "orign_page": "http://localhost:4200",
        "note": "test 3",
        "name": "test 3",
        "email": "test3@mail.ru",
        "rating": 4
    },
    {
        "age": '',
        "gender": '',
        "country": "",
        "orign_page": "http://localhost:4200",
        "note": "test 4",
        "name": "test 4",
        "email": "test4@mail.ru",
        "rating": 1
    },
    {
        "age": 61,
        "gender": 2,
        "country": "UKRAINE",
        "orign_page": "http://localhost:4200",
        "note": "test 5",
        "name": "test 5",
        "email": "test5@mail.ru",
        "rating": 5
    },
    {
        "age": 61,
        "gender": 1,
        "country": "SLOVENIA",
        "orign_page": "http://localhost:4200",
        "note": "test 6",
        "name": "test 6",
        "email": "test6@mail.ru",
        "rating": 5
    },
    {
        "age": 44,
        "gender": 2,
        "country": "SLOVENIA",
        "orign_page": "http://localhost:4200",
        "note": "test 7",
        "name": "test 7",
        "email": "test7@mail.ru",
        "rating": 3
    },
    {
        "age": '',
        "gender": '',
        "country": "",
        "orign_page": "http://localhost:4200",
        "note": "test 8",
        "name": "test 8",
        "email": "test8@mail.ru",
        "rating": 1
    },
]

const migrate = async function () {
    try {
        await Gender.insertMany(genders);
        await Country.insertMany(countries);
        await Review.insertMany(feadBack);
        Log('Data import was successful.')
        process.exit(0);
    } catch (error) {
        Log(error);
        process.exit(1);
    }
};

mongoose.connect(keys.mongodbURL)
    .then(() => {
        Log('MongoDB connected.');
        migrate();
    })
    .catch(error => Log(error));
